apiVersion: v1
kind: Template
metadata:
  name: workload-operator-deployment
  annotations:
    description: "This is Thoth - Workload Operator"
    openshift.io/display-name: "Thoth Core: Workload Operator"
    version: 0.1.2
    tags: thoth,workload-operator,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Workload
      Operator on OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: workload-operator-deployment
    app: thoth
    component: workload-operator

parameters:
  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - description: Project Name in which the operator is watching events.
    displayName: Operator Project Name
    required: true
    name: THOTH_OPERATOR_NAMESPACE

  - description: Service account allowing the Operator to schedule workload.
    displayName: Service account name.
    required: true
    name: THOTH_SERVICE_ACCOUNT_NAME

objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: workload-operator
      name: workload-operator-${THOTH_OPERATOR_NAMESPACE}
    spec:
      replicas: 1
      selector:
        name: workload-operator
      template:
        metadata:
          labels:
            app: thoth
            name: workload-operator
        spec:
          serviceAccountName: workload-operator-${THOTH_OPERATOR_NAMESPACE}
          containers:
            - name: workload-operator
              env:
                - name: KUBERNETES_API_URL
                  value: "https://kubernetes.default.svc.cluster.local"
                - name: KUBERNETES_VERIFY_TLS
                  value: "0"
                - name: THOTH_FRONTEND_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: frontend-namespace
                      name: thoth
                - name: THOTH_MIDDLETIER_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: middletier-namespace
                      name: thoth
                - name: THOTH_BACKEND_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: backend-namespace
                      name: thoth
                - name: THOTH_OPERATOR_NAMESPACE
                  value: "${THOTH_OPERATOR_NAMESPACE}"
                - name: THOTH_LOG_WORKLOAD_OPERATOR
                  value: INFO
                - name: THOTH_INFRA_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: infra-namespace
                      name: thoth
                - name: THOTH_AMUN_INFRA_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: amun-infra-namespace
                      name: amun
                - name: THOTH_AMUN_INSPECTION_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: amun-inspection-namespace
                      name: amun
                - name: PROMETHEUS_PUSHGATEWAY_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: prometheus-pushgateway-host
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-pushgateway-port
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "250m"
                limits:
                  memory: "384Mi"
                  cpu: "250m"
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - workload-operator
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_STREAM_NAMESPACE}"
              name: "workload-operator:${IMAGE_STREAM_TAG}"
